import pyautogui
import os
import time

def criar_tabela_mysql():
    pyautogui.alert('Executando criação de Table MySQL')
    pyautogui.moveTo(540, 235)
    pyautogui.leftClick()
    time.sleep(1.1)
    pyautogui.write('use cadastro')
    time.sleep(1.1)
    pyautogui.hotkey('ctrl','enter')
    time.sleep(1.1)
    pyautogui.hotkey('ctrl','a')
    time.sleep(1.1)
    pyautogui.press('del')
    time.sleep(1.1)
    os.startfile('C://Users/Joao/Desktop/Estrutura montagem.txt')
    time.sleep(1.1)
    pyautogui.hotkey('ctrl','a')
    time.sleep(1.1)
    pyautogui.hotkey('ctrl','c')
    time.sleep(1.1)
    pyautogui.leftClick()
    time.sleep(1.1)
    pyautogui.hotkey('ctrl','v')
    time.sleep(1.1)
    pyautogui.hotkey('ctrl','enter')
    time.sleep(1.1)
    pyautogui.hotkey('ctrl','a')
    time.sleep(1.1)
    pyautogui.press('del')
    time.sleep(1.1)
    pyautogui.write('insert into cursos values')
    time.sleep(1.1)
    pyautogui.press('enter')
    time.sleep(1.1)
    pyautogui.write("('1','Automacao Python BD', 'Curso Gratuito Online', 'Google','2021','Perfeito'),")
    time.sleep(1.1)
    pyautogui.press('enter')
    time.sleep(1.1)
    pyautogui.write("('2', 'Python BD', 'Praticando', 'MyExperience','2021','Desenvolvendo bem!');")
    time.sleep(1.1)
    pyautogui.hotkey('ctrl','enter')
    time.sleep(1.1)
    pyautogui.hotkey('ctrl','a')
    time.sleep(1.1)
    pyautogui.press('del')
    time.sleep(1.1)
    pyautogui.write('select * from cursos;')
    time.sleep(1.1)
    pyautogui.hotkey('ctrl','enter')
    time.sleep(1.5)
    pyautogui.hotkey('ctrl','a')
    time.sleep(1.2)
    pyautogui.press('del')
    time.sleep(1.1)
    pyautogui.write('alter table cursos')
    pyautogui.press('enter')
    time.sleep(1.1)
    pyautogui.write('add column matricula int')
    time.sleep(1.2)
    pyautogui.hotkey('ctrl','enter')
    time.sleep(1.2)
    pyautogui.hotkey('ctrl','a')
    time.sleep(1.2)
    pyautogui.press('del')
    time.sleep(1.2)
    pyautogui.write('select * from cursos')
    time.sleep(1.2)
    pyautogui.hotkey('ctrl','enter')
    time.sleep(1.3)
    pyautogui.hotkey('ctrl','a')
    time.sleep(1.2)
    pyautogui.press('del')
    time.sleep(1.2)
    pyautogui.write('insert into cursos values')
    time.sleep(1.1)
    pyautogui.press('enter')
    time.sleep(1.1)
    pyautogui.write("('3','Python BD', 'Praticando', 'YouTube','2021','Teste','10');")
    time.sleep(1.1)
    pyautogui.hotkey('ctrl','enter')
    time.sleep(1.2)
    pyautogui.hotkey('ctrl','a')
    time.sleep(1.1)
    pyautogui.press('del')
    time.sleep(1.1)
    pyautogui.write('update cursos')
    time.sleep(1.1)
    pyautogui.press('enter')
    time.sleep(1.1)
    pyautogui.write("set professor='My'")
    time.sleep(1.1)
    pyautogui.press('enter')
    time.sleep(1.1)
    pyautogui.write("where idcurso='3';")
    time.sleep(1.1)
    pyautogui.hotkey('ctrl','enter')
    time.sleep(1.2)
    pyautogui.hotkey('ctrl','a')
    time.sleep(1.1)
    pyautogui.press('del')
    time.sleep(1.2)
    pyautogui.write("select * from cursos")
    time.sleep(1.1)
    pyautogui.hotkey('ctrl','enter')
    time.sleep(1.5)
    pyautogui.hotkey('ctrl','a')
    time.sleep(1.2)
    pyautogui.press('del')
    time.sleep(1.2)
    pyautogui.write("drop table cursos;")
    time.sleep(1.1)
    pyautogui.hotkey('ctrl','enter')
    time.sleep(1.3)
    pyautogui.alert('Execução concluida com sucesso!')
    pass